server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: Credable

  jpa:
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # this line says hibernate for which plateform
   # hibernate has to prepare queries so that they can be run on that database without syntax error.
     #platform can be mysql, postgresql, mangodb etc
   hibernate:
     ddl-auto: update  # this line says hibernate that you have to add new tables, columns, or constraints as required, but it will not drop or modify existing schema objects. Existing data will be preserved.
     #ddl-auto: update --> this line says hibernate that  you  drop and recreate all the schema objects, including tables, columns, and constraints. This can result in data loss as existing data will be deleted.
     show-sql: true

   servlet:
     multipart:
       max-file-size: 10MB
       max-request-size: 10MB
  security:
    user:          #custom name, password and role
        name: Nitesh
        password: Mukati
        role: ADMIN
project:
   image: \image

logging:
  level:
    org:
     sprigframework:
      security: DEBUG


